VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IFindMyPeers"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'@Interface
Option Explicit

'===============================================================================

Public Function GetNeighborNext() As Shape
End Function

Public Function GetNeighborPrev() As Shape
End Function

Public Function GetPeers() As ShapeRange
End Function
